#!/usr/bin/env node
// Regenerates the static fallback hub page from a registry.
//   node build-hub.mjs [--registry <ports.json>]
//
// Writes hub.html next to the registry. That page works with nothing running at
// all — open it straight off disk. It can't start servers, and its liveness dots
// are a best-effort no-cors probe that some browsers block; run hubd.mjs for
// buttons and real TCP checks.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { page, computeProjects, resolveRegistry } from './hub-ui.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const registry = resolveRegistry(process.argv, [here, process.cwd(), 'E:/experiments']);

const reg = JSON.parse(readFileSync(registry, 'utf8'));
reg.root = reg.root || dirname(registry);

// Usage data is the daemon's to write; here it's read-only, so a static page
// built while hubd has been running still shows sensible tiers.
let state = { lastSeen: {} };
try { state = JSON.parse(readFileSync(resolve(dirname(registry), 'hub-state.json'), 'utf8')); }
catch {}

const projects = computeProjects(reg, state);

const out = resolve(dirname(registry), 'hub.html');
writeFileSync(
  out,
  page({
    projects,
    interactive: false,
    footer:
      'Static snapshot of <code>' + registry + '</code>, generated by <code>build-hub.mjs</code> — ' +
      're-run it after editing the registry. For Start/Stop buttons and reliable liveness, ' +
      'run <code>node hubd.mjs</code> and use <code>http://localhost:7777</code> instead.',
  })
);

const clashes = new Set(projects.filter((p) => p.clash).map((p) => p.port));
console.log(`${out} — ${projects.length} projects, ${clashes.size} port collisions`);
